version: "3.8"

services:
  application:
    build:
      context: .
      dockerfile: Dockerfile

    volumes:
      - ..:/workspace/project/:cached
      - /var/run/docker.sock:/var/run/docker-host.sock
    # Runs app on the same network as the postgres container, allows "forwardPorts" in devcontainer.json function.
    network_mode: service:postgres

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

  postgres:
    image: postgres:15.2
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: core_dev

volumes:
  postgres-data:
